### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ankane** [ankane/production_rails#11]
Hi, @jasiekmiko and @itsderek23, thanks for contributing! This repo doesn't currently have a license, which isn't great, so I'd like to license it under the [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/) license. To do that, I'd like to get approval from all contributors.

Do you agree to license your contribution(s) under the Creative Commons Attribution 4.0 International license? If so, please comment "I agree" below.

**Comment by jasiekmiko** [comment]
I agree

**Comment by itsderek23** [comment]
I agree

**Comment by ankane** [comment]
License added. Thanks again for contributing!
