### ISSUE TITLE
Uptime & Error tracking

### ISSUE THREAD

**Issue by spaquet** [ankane/production_rails#12]
I think you should add **Honeybadger** to the list.
They are first known for error tracking in production but they also have a good uptime monitoring service.

Sentry should also be mentioned when it comes to monitoring.

[Honeybadger](https://www.honeybadger.io)
[Sentry](https://sentry.io)

**Comment by ankane** [comment]
Hi @spaquet, thanks for the suggestion, but it's not meant to be a comprehensive list of gems / services (see Awesome Ruby for that).
