### ISSUE TITLE
(Suggestion) Compile Ruby with jemalloc to get better memory perf than glibc's malloc

### ISSUE THREAD

**Issue by abevoelker** [ankane/production_rails#6]
Using jemalloc (supposedly) results in lower overall memory usage and lower fragmentation than the standard glibc malloc you get by default when running Ruby on Linux: https://www.levups.com/en/blog/2017/optimize_ruby_memory_usage_jemalloc_heroku_scalingo.html

**Comment by ankane** [comment]
Hey @abevoelker, thanks for sharing 👍  I hadn't heard of this before (or obviously tried it) in a production environment, so not comfortable adding it as a recommendation right now, but it's an interesting idea.

**Comment by abevoelker** [comment]
Fair enough :v: Thanks for the guide and all the useful gems!
