### ISSUE TITLE
Add Geocoding for production?

### ISSUE THREAD

**Issue by massens** [ankane/production_rails#7]
Maybe add the geocoding specs that you have in https://github.com/ankane/ahoy/blob/master/README.md as a production best practice?

--------------------------------------------
## Geocoding Performance

To avoid calls to a remote API, download the [GeoLite2 City database](https://dev.maxmind.com/geoip/geoip2/geolite2/) and configure Geocoder to use it.

Add this line to your application’s Gemfile:

```ruby
gem 'maxminddb'
```

And create an initializer at `config/initializers/geocoder.rb` with:

```ruby
Geocoder.configure(
  ip_lookup: :geoip2,
  geoip2: {
    file: Rails.root.join("lib", "GeoLite2-City.mmdb")
  }
)
```

**Comment by ankane** [comment]
Hey @massens, thanks for the suggestion 👍 My first thought is that it's a bit too specialized to include.
